<?php
/**
 * @file
 * Provide profile data of logged in user as personalized setting.
 */

/**
 * Implements hook_authcache_p13n_setting().
 */
function authcache_user_authcache_p13n_setting() {
  return array(
    'user' => array(
      'admin name' => t('User'),
      'admin group' => t('Logged in User'),
      'admin description' => t('Provide profile data of logged in user as personalized setting'),
      'setting' => array(
        '#setting' => 'u',
        '#target' => 'authcacheUser',
        '#class' => 'AuthcacheUserSetting',
        '#arguments' => array(
          array(
            'uid',
            'name',
            'mail',
          ),
        ),
      ),
      'cache maxage' => 86400,
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function authcache_user_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  if ($user->uid && authcache_page_is_cacheable()) {
    switch ($form_id) {
      case 'contact_site_form':
      case 'contact_personal_form':
        if (isset($form['name'])) {
          authcache_user_attach_property($form['name'], 'name');
        }
        if (isset($form['mail'])) {
          authcache_user_attach_property($form['mail'], 'mail');
        }
        break;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Replace the username in the comment-form with a placeholder.
 */
function authcache_user_form_comment_form_alter(&$form, &$form_state) {
  global $user;

  if ($user->uid && isset($form['author']['_author']) && !authcache_element_is_cacheable($form['author']['_author'])) {
    $replacement = array(
      '#theme' => 'html_tag',
      '#tag' => 'span',
    );
    authcache_user_attach_property($replacement, 'name');
    $form['author']['_author']['#markup'] = render($replacement);
    authcache_element_set_cacheable($form['author']['_author']);
  }
}

/**
 * Attach setting loader for currently logged in user to the given element.
 */
function authcache_user_attach_property(&$element, $property_name) {
  $p13n_setting = array(
    '#setting' => 'user',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'authcache_user') . '/authcache_user.js'),
    ),
  );
  $element['#attached']['authcache_p13n_add_setting'][] = array($p13n_setting);
  $element['#attributes']['class'][] = 'authcache-user';
  $element['#attributes']['data-p13n-user-prop'] = $property_name;
}
