<?php
/**
 * @file
 * Authcache support for forum module.
 */

/**
 * Implements hook_authcache_p13n_assembly().
 */
function authcache_forum_authcache_p13n_assembly() {
  return array(
    'forum-list' => array(
      'admin name' => t('Forum list'),
      'admin group' => t('Forum'),
      'admin description' => t('Mark forums with new topics in forum list.'),
      'fragment' => array(
        '#partial' => 'new',
        '#class' => 'AuthcacheForumListNewTopicsFragment',
      ),
      'cache maxage' => 600,
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Remove number of new topics from forum overview page.
 */
function authcache_forum_preprocess_forum_list(&$variables) {
  global $user;

  // Defer the "new" marker for user.
  if ($user->uid && authcache_page_is_cacheable()) {
    foreach ($variables['forums'] as $forum) {
      // Remove personalized information from forum list.
      $forum->new_text = '';
      $forum->new_url = '';
      $forum->new_topics = '';
      $forum->icon_class = 'default';
      $forum->icon_title = t('No new posts');
      $forum->old_topics = $forum->num_topics;

      if ($forum->num_topics) {
        $forum->num_topics .= '<br/>';
        $forum->num_topics .= theme('authcache_p13n_partial', array(
          'assembly' => 'forum-list',
          'partial' => 'new',
          'param' => $forum->tid,
        ));
      }
    }

    drupal_add_js(drupal_get_path('module', 'authcache_forum') . '/authcache_forum.js');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Remove new-icon from forum topic icon.
 */
function authcache_forum_preprocess_forum_icon(&$variables) {
  global $user;

  if ($user->uid && authcache_page_is_cacheable()) {
    $variables['new_posts'] = 0;

    if (strpos($variables['icon_class'], 'hot') !== FALSE) {
      $variables['icon_class'] = 'hot';
      $variables['icon_title'] = t('Hot topic');
    }
    elseif (preg_match('/new|default/', $variables['icon_class'])) {
      $variables['icon_class'] = 'default';
      $variables['icon_title'] = t('Normal topic');
    }

    drupal_add_js(drupal_get_path('module', 'authcache_forum') . '/authcache_forum.js');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Remove number of new comments counter from topic and instead inject number of
 * new comments partial from the authcache comment module.
 */
function authcache_forum_preprocess_forum_topic_list(&$variables) {
  global $user;

  if ($user->uid && authcache_page_is_cacheable()) {
    foreach ($variables['topics'] as $topic) {
      if ($topic->comment_count) {
        $topic->comment_count .= '<br/>';
        $topic->comment_count .= theme('authcache_p13n_partial', array(
          'assembly' => 'comment-num-new',
          'partial' => 'new',
          'param' => $topic->nid,
          'original' => $topic->new_text,
        ));
        $topic->new_text = '';
        $topic->new_url = '';

        drupal_add_js(drupal_get_path('module', 'authcache_forum') . '/authcache_forum.js');
      }
    }
  }
}
